### ISSUE TITLE
trainer.train()微调失败

### ISSUE THREAD

**Issue by yijianfenghou** [Zeyi-Lin/LLM-Finetune#1]
运行train_glm4_ner.py文件的时候，出现CUDA error: misaligned address错误，刚开始以为是显存过少导致失败，降低加载预训练模精度，还是出现同样的失败，不清楚是什么原因导致？麻烦能解决解答一下嘛？

**Comment by Zeyi-Lin** [comment]
我没有遇到类似问题，可以试试在运行train train_glm4_ner.py之前，先：
```bash
export CUDA_VISIBLE_DEVICES=0
```
试一下

**Comment by yijianfenghou** [comment]
> 我没有遇到类似问题，可以试试在运行train train_glm4_ner.py之前，先：
> 
> ```shell
> export CUDA_VISIBLE_DEVICES=0
> ```
> 
> 试一下

谢谢啦，我这边改小了batch_size就可以了

**Comment by Zeyi-Lin** [comment]
> > 我没有遇到类似问题，可以试试在运行train train_glm4_ner.py之前，先：
> > ```shell
> > export CUDA_VISIBLE_DEVICES=0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 试一下
> 
> 谢谢啦，我这边改小了batch_size就可以了

🎉
